### ISSUE TITLE
Non matching type in examples

### ISSUE THREAD

**Issue by MarelliF** [SodaqMoja/Sodaq_RN2483#7]
Hello,

I am having trouble using your library.
In the provided examples, 
`initABP(loraSerial, devAddr, appSKey, nwkSKey, true)`
causes an error : 
_error: no matching function for call to 'Sodaq_RN2483::initABP(USARTClass&, const uint8_t [4], const uint8_t [16], const uint8_t [16], int)'_

It seems there is a type incompatibility between Serial1 and Stream. I tried casting
`(Stream)Serial1`
but it is impossible to instantiate the abstract element Stream.

How can I run your example without errors ?

Regards,
François

**Comment by Daniel-dk** [comment]
What board are you using it on ?

the "Serial" objects can be  "USARTclass", "UARTclass" or "Uart" depeding on the board ( and cpu ) you are using.

**Comment by MarelliF** [comment]
I am using arduino Due.
It seems to be USARTClass.

**Comment by Daniel-dk** [comment]
I made a pull request to add this to the library ( but only for the UARTclass- i used "Serial" on the due, not Serial1 ), you can easily replicate it ...

https://github.com/SodaqMoja/Sodaq_RN2483/pull/6/files

edit **Sodaq_RN2483.h line 58**  and replace this 

```
#elif defined(ARDUINO_ARCH_SAM) || defined(ARDUINO_ARCH_SAMD)
typedef Uart SerialType;
```

with this:

```
#elif  defined(ARDUINO_ARCH_SAMD)
 typedef Uart SerialType;
#elif defined(ARDUINO_ARCH_SAM) 
//typedef UARTClass SerialType; // "Serial"
typedef USARTClass SerialType; // "Serial1, Serial2,Serial3, Serial4 "
```

you might also run into errors with the watchdog settings:
I also changed **Sodaq_wdt.h, line 28** from this:
`#elif ARDUINO_ARCH_SAMD`
to this :
`#elif ARDUINO_ARCH_SAMD || ARDUINO_ARCH_SAM`

we'd have to find a better way of handling the different types of Serial objects, Stream might be simpler ( less things to handle ? ) - I don't think we can do multiple typedefs for the same thing
could also create an overloaded function for USARTClass, UARTClass and Uart .. will test at some point and then submit a new pull requst

**Comment by MarelliF** [comment]
Thanks a lot for your help, it worked fine.
